-- NFL Teams (32 teams)
INSERT INTO teams (league_id, name, abbreviation, city) VALUES
(1, 'Buffalo Bills', 'BUF', 'Buffalo'),
(1, 'Miami Dolphins', 'MIA', 'Miami'),
(1, 'New England Patriots', 'NE', 'New England'),
(1, 'New York Jets', 'NYJ', 'New York'),
(1, 'Baltimore Ravens', 'BAL', 'Baltimore'),
(1, 'Pittsburgh Steelers', 'PIT', 'Pittsburgh'),
(1, 'Cleveland Browns', 'CLE', 'Cleveland'),
(1, 'Cincinnati Bengals', 'CIN', 'Cincinnati'),
(1, 'Houston Texans', 'HOU', 'Houston'),
(1, 'Indianapolis Colts', 'IND', 'Indianapolis'),
(1, 'Jacksonville Jaguars', 'JAX', 'Jacksonville'),
(1, 'Tennessee Titans', 'TEN', 'Tennessee'),
(1, 'Kansas City Chiefs', 'KC', 'Kansas City'),
(1, 'Denver Broncos', 'DEN', 'Denver'),
(1, 'Las Vegas Raiders', 'LV', 'Las Vegas'),
(1, 'Los Angeles Chargers', 'LAC', 'Los Angeles'),
(1, 'Dallas Cowboys', 'DAL', 'Dallas'),
(1, 'Philadelphia Eagles', 'PHI', 'Philadelphia'),
(1, 'Washington Commanders', 'WAS', 'Washington'),
(1, 'New York Giants', 'NYG', 'New York'),
(1, 'Green Bay Packers', 'GB', 'Green Bay'),
(1, 'Detroit Lions', 'DET', 'Detroit'),
(1, 'Chicago Bears', 'CHI', 'Chicago'),
(1, 'Minnesota Vikings', 'MIN', 'Minnesota'),
(1, 'Atlanta Falcons', 'ATL', 'Atlanta'),
(1, 'New Orleans Saints', 'NO', 'New Orleans'),
(1, 'Tampa Bay Buccaneers', 'TB', 'Tampa Bay'),
(1, 'Carolina Panthers', 'CAR', 'Carolina'),
(1, 'San Francisco 49ers', 'SF', 'San Francisco'),
(1, 'Los Angeles Rams', 'LAR', 'Los Angeles'),
(1, 'Seattle Seahawks', 'SEA', 'Seattle'),
(1, 'Arizona Cardinals', 'ARI', 'Arizona');
